name: Build ts
run-name: Testing
on:
  workflow_dispatch:
  push:
    branches:
     - main
  pull:
    branches:
     - main

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
 job_1:
    name: Build stuff
    runs-on: windows-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.x
        cache: npm

    - name: Install
      run: npm ci

    - name: Build
      run: npm run build