name: Create branch
run-name: Create branch
on:
  workflow_dispatch:
    inputs: 
      name:
        type: string
        required: true
      content:
        type: string
        required: true

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} ${{ inputs.name }}'
  cancel-in-progress: true

jobs:
  build_stuff:
    runs-on: windows-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3 

     - name: configure git
       run: |
            git config --global user.email "filebot@example.com"
            git config --global user.name "File Bot"

     - name: Create branch
       run: |
          git checkout -b new-file-%name%
          echo %content% > %name%.md
          git add %name%.md
          git commit -m "Added new file"
          git push -u origin new-file-%name%
       env:
          name: ${{ inputs.name }}
          content: ${{ inputs.content }}